version: '2'

volumes:
    skeleton-webserver-data:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7.34
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3307:3307
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: skeleton
            MYSQL_TCP_PORT: 3307
        volumes:
            - skeleton-webserver-data:/var/lib/mysql