
const constants = {
    NOT_FOUND: "NOT_FOUND",
    ALREADY_EXISTS: "ALREADY_EXISTS",
    TOKEN_REVOKED: "TOKEN_REVOKED",
    MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
    PASSWORD_NOT_MATCH: "PASSWORD_NOT_MATCH",
    WRONG_CREDENTIALS: "WRONG_CREDENTIALS",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    EMPTY_BODY: "EMPTY_BODY",
    ALREADY_IN_USE: "ALREADY_IN_USE",
    INVALID_EMAIL: "INVALID_EMAIL"
};

module.exports = Object.freeze(constants);
